### ISSUE TITLE
Perun Network

### ISSUE THREAD

**Issue by ManyRios** [raid-guild/indexed#106]
## Reference
- [Perun Wiki](https://github.com/perun-network/go-perun/wiki)
- [Eth L2](https://ethereum.org/en/developers/docs/layer-2-scaling/)

Perun is an off-chain framework that supports real-time payments as well as complex business logic and superchargin any existing blockchain

## Chain Name
     Perun
## Chain Type (Plasma, ZKSNARK, etc)
     State channels
     Allow participants to transact x number of times off-chain while only submitting two transaction to the network on chain. This allows for extremely high transaction throughput
## Average Tx Cost
     6600000 gwei/tx
## Consensus Mechanism (PoW, PoS)
      State Channel(off-chain) - Proof of Stake( PoS )
## Max Transactions Per Second (TPS)
     >10k/seg (Instant)
## Social media and community links

- [Website](https://perun.network/)
- [Github](https://github.com/perun-network/go-perun)
- [Twitter](https://twitter.com/perunnetwork)
- [Medium](https://medium.com/perunnetwork)
- [Linkedin](https://www.linkedin.com/company/perun-network/)
- [Facebook](https://www.facebook.com/perun.network/)

**Comment by YalorMewn** [comment]
Thanks for submitting, but Perun was not on this list of project we are willing to pay for a submission.

**Comment by ManyRios** [comment]
Dragonchain https://github.com/raid-guild/indexed/issues/86 is on your "list"

**Comment by ManyRios** [comment]
Hi @YalorMewn  you paid for a celer update.. but it's not in your list 

I summited 6 and 1 of them it's DRAGONCHAIN and it is in the list 

![image](https://user-images.githubusercontent.com/34518489/108448775-ba0bc280-7238-11eb-959f-10c766778c78.png)
