### ISSUE TITLE
GLUON NETWORK

### ISSUE THREAD

**Issue by ManyRios** [raid-guild/indexed#108]
Gluon is a purpose built sidechain which is designed to avoid the drawbacks of Ethereum.

## References
- [Research](https://ethresear.ch/t/gluon-plasma-full-spec-for-non-custodial-exchanges/3931/2)
- [Gluon Doc](https://gluon.network/wp-content/uploads/2020/10/GluonPlasma.pdf)
- [Eth Sc](https://etherscan.io/tx/0x5cc882de1866940dd0803256d5adba5813774c4cdf2fd25d6b4fac48ac65ed80/advanced)
- [Whitepaper](https://github.com/gluonnetwork/whitepaper)

## Chain Name
     Gluon Network
## Chain Type (Plasma, ZKSNARK, etc)
     Plasma
     A plasma chain is a separate blockchain that is anchored to the main Ethereum chain, and uses fraud proofs (like Optimistic rollups) to arbitrate disputes.
## Average Tx Cost
     180 Gwei/tx
## Consensus Mechanism (PoW, PoS)
     Proof of Stake(PoS)
## Max Transactions Per Second (TPS)
     >3000/s
## Social media and community links

- [Website](https://gluon.network/)
- [Github](https://github.com/gluonnetwork/)
- [Twitter](https://twitter.com/gluonnetwork)

**Comment by chair28980** [comment]
@ManyRios Hallo!

Can you migrate the pertinent data here to the form here: https://docs.google.com/forms/d/e/1FAIpQLScbMNeGoQEOrvuuvrk6xaZvdE2PzKiALAMcZ14v48ARS4fIHg/viewform

Sorry for the double data entry for you, I'm updating the instructions now.

**Comment by ManyRios** [comment]
> @ManyRios Hallo!
> 
> Can you migrate the pertinent data here to the form here: https://docs.google.com/forms/d/e/1FAIpQLScbMNeGoQEOrvuuvrk6xaZvdE2PzKiALAMcZ14v48ARS4fIHg/viewform
> 
> Sorry for the double data entry for you, I'm updating the instructions now.

done with this one
