### ISSUE TITLE
Decentraland

### ISSUE THREAD

**Issue by ManyRios** [raid-guild/indexed#116]
Decentraland is a virtual reality platform powered by the Ethereum blockchain. Users can create, experience, and monetize content and applications using a developer toolkit that works on any platform (all VR headsets and web browsers) and is designed to create virtual environments and applications in no time.

##  Reference
     - [Blog](https://decentraland.org/blog/technology/decentralands-path-toward-scaling-transactions/)
     - [docs ](https://docs.decentraland.org/)
## Chain Name
     Matic Network
## Chain Type (Plasma, ZKSNARK, etc)
     Plasma
## Average Tx Cost
     7.3021 Gwei
## Consensus Mechanism (PoW, PoS)
     PoS
## Max Transactions Per Second (TPS)
     7200
## Social media and community links

- [Website](https://decentraland.org/)
- [Github](https://github.com/decentraland)
- [Twitter](https://twitter.com/decentraland)
- [Reddit](https://reddit.com/r/decentraland)
- [Discord](https://dcl.gg/discord)

**Comment by chair28980** [comment]
@ManyRios I'm not sure that Decentraland counts as a Layer 2 service/solution. If it is indeed built on TOP of Matic.

**Comment by ManyRios** [comment]
is a sercive

**Comment by ManyRios** [comment]
Hi! remember I made 6 issues :)

**Comment by YalorMewn** [comment]
At this point your submissions are just spam @ManyRios so please discontinue. You clearly did not read the instructions for what was eligible for funding.

**Comment by ManyRios** [comment]
This was 20 days ago...
