### ISSUE TITLE
TPS numbers are misleading and require more nuance

### ISSUE THREAD

**Issue by tasdienes** [raid-guild/indexed#120]
The TPS figures are misleading and require more nuance.  

Because rollups write all Tx data to L1, rollup throughput is constrained by how much data L1 can take.  The quoted max TPS numbers that get thrown around are generally for all rollup chains combined, assuming that L1 blocks are otherwise empty, which is obviously a terrible assumption.  All rollup chains, including rollups from different vendors, must share the L1 capacity.

The situation is different for things like plasma and validium that do not write all Tx data to L1.  The max TPS may apply to each instance of the L2, which may be additive.  The max TPS for each instance of this type of L2 is not constrained by L1, and you can get more total TPS by running multiple L2 instances.

**Comment by chair28980** [comment]
@tasdienes Hallo! Thank you for your feedback, this is exactly what I'm looking for. As this site comes together it's becoming clear that there is a challenge displaying accurate and updated TPS data, as well as comparing the data across different services.

We will constantly be revisiting how to best display relevant data, at the moment we are parsing the existing information and updating.

I will keep this issue open and revisit shortly with more specific questions for you about a better approach displaying and comparing TPS data, if thats cool with you!

**Comment by tasdienes** [comment]
Sounds good.  Another thought: it may be helpful to quote simple transaction cost (gas/tx) for rollups, which is probably a more useful number than TPS when comparing them.  It's more complicated to estimate Tx cost for non-rollups, but more straightforward to do that for rollups.

**Comment by chair28980** [comment]
@tasdienes circling back to this, there will be many updates pushed this weekend.

We are debating whether or not comparing data on the homepage table the way we are currently is the best approach, do you have any suggestions as to what might be better to display on the site's homepage?

**Comment by tasdienes** [comment]
To be correctly understood, TPS figures need so many asterisks and caveats that it's very difficult and somewhat misleading to compare them directly. It might be even be better to put them into bins like <1000, 1000-5000, 5000-25,000, etc.  so that people don't take them too literally and just look for the biggest number.

I'd also avoid comparing TPS for rollups and non-rollups since they are totally different things.  Maybe they need different terms.  Rollup potential throughput should have a giant * with an explanation of what it means, and how unrealistic it is.
