### ISSUE TITLE
Problems with "Cost of 100 transactions" and "Finality time" fields in new submission form

### ISSUE THREAD

**Issue by DZGoldman** [raid-guild/indexed#125]
Hey, I just submitted an entry (for Aribtrum) via the [new form](https://docs.google.com/forms/d/e/1FAIpQLScbMNeGoQEOrvuuvrk6xaZvdE2PzKiALAMcZ14v48ARS4fIHg/viewform). This definitely looks like it will be a big step in the right direction!. Inevitably, things are going to get a bit complex and tricky, (which is fine, perfect as enemy of good, etc.), but there are still 2 fields that I wanted to flag as being majorly problematic in their current form:

1. **"Cost of 100 transactionsIn US dollars, how much does it cost to make 100 transactions, on average (float only)"**

     - This should simply be removed. First off, as well all know, the USD cost of transactions on L1 itself is constantly changing. For most (if not all) L2 protocols,  L2 cost will bear some relationship to L1 cost; thus, this question only starts to make sense if the question itself assumes a specific L1 cost, which it doesn't. But furthermore, anticipating the US dollar cost of transactions within an L2 itself is contingent on a number of complex factors and is still going to be widely speculative, even for the projects already on mainnet. There's no way we'll end up with an apples to apples comparison. Anything useful here can already be gleaned from the "TPS" fields, thus this field strictly subtracts info/clarity.

2. **Finality time
How long does it take to achieve finality, on average, in HOURS (float only)**

    - If this is going to be included, it needs to allow a paragraph, not just a float. On (e.g.) Arbitrum and several other L2s, the finality is "the same as layer 1," which even itself is subjective (i.e., the number of block confirmations one chooses to wait), and can't be conveyed via a float. This category will inevitably get messy as finality is generally subjective, and begets the question of "under what assumptions," etc., which different projects will interpret differently. But in any case, allowing for an explanation would help; I can't think of any example where a simple number would be sufficient. 
    
Thanks! 

(I'm assuming this is the best forum to have this discussion; if feedback has moved elsewhere do let know).

**Comment by chair28980** [comment]
@DZGoldman Thank you for your submission! Will circle back shortly to inspect, reply and update!

**Comment by chair28980** [comment]
@DZGoldman delays! This is still on my radar, hoping to get to it today or tomorrow.

**Comment by chair28980** [comment]
Response and convo in: https://github.com/raid-guild/indexed/issues/138
