### ISSUE TITLE
Connext

### ISSUE THREAD

**Issue by rhlsthrm** [raid-guild/indexed#18]
## Name
Connext

## Links (github/social)
https://connext.network
https://twitter.com/ConnextNetwork
https://github.com/connext
https://discord.gg/raNmNb5

## Tx Cost
0 fees for txs. Node operators can optionally charge fees to route txs through the network.

## Finality
Instant

## Consensus
State channel, i.e. consensus only required between channel participants.

## $ Efficient
Extremely cost-efficient for users, the highest cost is the cost of collateral, which is required to be provided by node operators.

## Max TPS
1000+ (limit not tested)

## Additional Info
Please reach out in our discord for more info!

**Comment by chair28980** [comment]
Site updated
