### ISSUE TITLE
Immutable X 

### ISSUE THREAD

**Issue by 0xperks** [raid-guild/indexed#46]
Name: Immutable X
Links: https://immutable.com
Type: ZK Rollup
Transaction cost: Free
Finality: Instant
Consensus: STARK Zero-Knowledge Proof
Max TPS: 9,000+
Additional Info: Developed in partnership with StarkWare, simple API-based minting & exchange of NFTs, ERC-20s for developers.

**Comment by chair28980** [comment]
@tperks hello! Thank you for opening the issue! If you'd like to contribute toward the gitcoin grant work, please see the details here: https://github.com/raid-guild/indexed/issues/30  and open a new pull request with the data here: https://github.com/raid-guild/indexed/pulls

Thank you!
