### ISSUE TITLE
Fuel

### ISSUE THREAD

**Issue by aadorian** [raid-guild/indexed#49]
Name: Fuel
Links https://mainnet.fuel.sh/network
Tx Cost:~1350-1600 gas (~0.03 USD)
Finality:  Proof of work
Consensus:Probablistic
Max TPS:Max TPS: 320.3ms

<img width="1101" alt="Screen Shot 2021-01-16 at 2 17 13 AM" src="https://user-images.githubusercontent.com/734790/104797923-0333a700-57a1-11eb-9d67-d5fb53c92462.png">

**Comment by chair28980** [comment]
@aadorian hello! Thank you for opening the issue! If you'd like to contribute toward the gitcoin grant work, please see the details here: https://github.com/raid-guild/indexed/issues/30 and open a new pull request with the data here: https://github.com/raid-guild/indexed/pulls

Thank you!

**Comment by aadorian** [comment]
> @aadorian hello! Thank you for opening the issue! If you'd like to contribute toward the gitcoin grant work, please see the details here: #30 and open a new pull request with the data here: https://github.com/raid-guild/indexed/pulls
> 
> Thank you!

Excellent!!! Thank you !!
