### ISSUE TITLE
Solana

### ISSUE THREAD

**Issue by aadorian** [raid-guild/indexed#50]
Name: Solana
Links: https://solana.com/ , https://solana.com/es/validators , https://docs.solana.com/proposals/block-confirmation#finality-and-payouts, https://docs.solana.com/cluster/synchronization#relationship-to-consensus-mechanisms , https://docs.solana.com/cluster/performance-metrics#tps
Tx cost (average): $0.00001 Avg. Fee Per Transaction
Consensus:  Proof of Stake
Finality: No Cross-block State Initially
Max TPS: 2 sec period

**Comment by chair28980** [comment]
https://github.com/raid-guild/indexed/pull/36
