### ISSUE TITLE
MaticNetwork

### ISSUE THREAD

**Issue by subakteam** [raid-guild/indexed#58]
Type#
POS + Plasma

Tx Cost#
0.00001

Finality#
2 seconds on Layer2, 30-45mins checkpoints on Ethereum

Consensus#
POS (Tendermint)

$ Efficient#
Yes

Max TPS#
7200 per public-shared sidechain, multiple sidechains possible

**Comment by chair28980** [comment]
@subakteam hello! thank you for your submission! Someone beat you to the punch! Check out Celer, Dapp Solutions, Dragonchain, Everest, Hubble Project, KChannels, Meter or Serv.

Please include as muuuuuch info as you can find, including social media and community links (discord/telegram), thank you!
