### ISSUE TITLE
 Dragonchain 

### ISSUE THREAD

**Issue by ManyRios** [raid-guild/indexed#86]
Reference:
- [Reddit](https://www.reddit.com/r/ethereum/comments/i023gf/dragonchain_great_reddit_scaling_bakeoff_public/)
- [DragonChain Docs](https://docs.dragonchain.com/)
- [Eth L2 ](https://ethereum.org/en/developers/docs/layer-2-scaling/)
- [Github](https://github.com/dragonchain/dragonchain)
- [`Video`](https://www.youtube.com/watch?v=pSfBid1_US4&feature=youtu.be)

Chain Name: 
  DragonChain 
    Dragonchain is an enterprise and start up ready platform to build flexible and scalable blockchain applications.
Chain Type: 
   Hybrid Solution.
       (Combine the best parts of multiple layer 2 technologies, and may offer configurable tradeoffs.)
Average Tx cost (average): 
   100000 gwei/txn
Consensus: 
  Proof of work (POW)
Max TPS: 
   2800/s

Social Links: 

- [Website](https://dragonchain.com/)
- [Twitter](https://twitter.com/dragonchaingang/)
- [Linkedin](https://www.linkedin.com/company/18216867/)
- [Telegram](https://t.me/dragontalk/)
- [Facebook](https://facebook.com/Dragonchaingang/)
- [Youtube](https://www.youtube.com/c/DragonchainOfficial)

**Comment by YalorMewn** [comment]
@ManyRios please read the submission requirements carefully, the txn cost needs to be in gwei not $000.1 

$0.0001/txn >>> gwei 

Also, please specify what "hybrid solution" means in the docs page, we'll consider this submission incomplete until you make those changes.

**Comment by ManyRios** [comment]
Updated

**Comment by ManyRios** [comment]
Done with the 3 issues submitted by me to the google forms
